name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run lint checks
        run: ./gradlew lint

      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [ lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run tests
        run: ./gradlew test

      - name: Generate reports
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: app/build/reports/jacoco/coverage

  #      - name: Download Reports Folder
  #        uses: actions/download-artifact@v2
  #        with:
  #          name: report
  #          path: app/build/reports/jacoco/coverage

  #  disabled for now
  #  instrumentation-test:
  #    needs: [unit-test]
  #    runs-on: macos-latest
  #    steps:
  #      - name: Checkout the code
  #        uses: actions/checkout@v2
  #
  #      - name: Run espresso tests
  #        uses: reactivecircus/android-emulator-runner@v2
  #        with:
  #          api-level: 29
  #          script: ./gradlew connectedCheck
  #
  #      - name: Upload test report
  #        uses: actions/upload-artifact@v2
  #        with:
  #          name: instrumentation_test_report
  #          path: app/build/reports/androidTests/connected/


  static-code-analysis:
    needs: [ unit-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonarqube --info

#       - name: SonarCloud Scan
#         run: ./gradlew app:sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }}
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#   package:
#     needs: [static-code-analysis]
#     name: Generate APK
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout the code
#         uses: actions/checkout@v2

#       - name: set up JDK 1.8
#         uses: actions/setup-java@v1
#         with:
#           java-version: 1.8

#       - name: Build debug APK
#         run: ./gradlew assembleDebug --stacktrace

#       - name: Upload APK
#         uses: actions/upload-artifact@v2
#         with:
#           name: blueprint.apk
#           path: app/build/outputs/apk/debug/app-debug.apk
